config/routes.rb
Rails.application.routes.draw do
  root 'weathers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :weathers, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    @response = Weather::SearchService.new(params[:q]).execute if params[:q]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Raye7Challenge
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/weathers/index.html.haml
%h1 Weather Search
= form_with url: weathers_path, method: :get, local:true, scope: :q do |form|
  .form-group
    = form.label :city_name
    = form.text_field :city_name, value: params[:q] && params[:q][:city_name]
  .form-group
    = form.label :country_code
    = form.text_field :country_code, value: params[:q] && params[:q][:country_code]

  = form.submit :submit

%br
= render "weathers/responses/#{@response['cod']}" if @response

app/views/weathers/responses/_200.html.haml
%br
Results for #{@response['name']}
%br
- @response['main'].each do |key, value|
  = label_tag key.to_sym
  = label_tag value
  %br

app/views/weathers/responses/_404.html.haml
%br
city not found